### ISSUE TITLE
IDataObject doesn't match the tests

### ISSUE THREAD

**Issue by Penfu** [CPNV-ES-BI/BI_CSHARP_GCP#1]
## Problematic

The current interface doesn't match the given unit tests.

## Exemple

The test 'CreateObject_PathNotExists_ObjectExists' can't be implemented because there is no used of path in CreateObject method.

## Todo

Update the interface to match tests.

**Comment by NicolasGlassey** [comment]
@Penfu 

Je ne sais pas si cette issue m'est destinée, mais étant en travail de review, je passe par ici.

Toutes les méthodes du DataObject doivent s'adapter à deux cas particuliers:
* soit on parle de l'objet "root" (bucket, blob)
* soit on parle d'un sous élément à l'objet "root"

Donc parfois, il n'y a pas de paramètres car on parle du "root" object qui est un attribut privé de la classe (donc inutile de le repasser en paramètre).

A dispo si besoin !

**Comment by Penfu** [comment]
Solve in this PR #4
