### ISSUE TITLE
Compilation du projet

### ISSUE THREAD

**Issue by NicolasGlassey** [CPNV-ES-BI/BI_CSHARP_GCP#2]
@MauroWasTaken 

En regardant votre docker file, je remarque la comment 
```
donet restore
```

En regardant la document officielle, je ne suis pas sur que ce soit le bon choix.
Vous me validez cela en le documentant dans le wiki ?

Merci !

**Comment by MauroWasTaken** [comment]
Effectivement, la commande `dotnet restore` est executée automatiquement quand on fait la commande `dotnet build ` 
Les changements ont été faits
