### ISSUE TITLE
Review Repository

### ISSUE THREAD

**Issue by NicolasGlassey** [CPNV-ES-BI/BI_CSHARP_GCP#3]
@MauroWasTaken  @Penfu 

Voici mes premiers retours sur la partie dépôt.

Vous êtes efficaces, faites juste attention de bien respecter les conventions de nommage et la stratégie (que vous prenez en entier).

https://cpnv1.sharepoint.com/:x:/r/sites/22_23_BI_SiT2a/Documents%20partages/General/CPNV_BI_Eval_Grid_Team.xlsx?d=wfe0e16ad510d41e3a90301db04bc6ae7&csf=1&web=1&e=fFSkXT

**Comment by Penfu** [comment]
@MauroWasTaken and I have taken into account your feedback and paid attention to the different points mentioned.
