### ISSUE TITLE
Google access token expires after a certain time

### ISSUE THREAD

**Issue by MauroWasTaken** [CPNV-ES-BI/BI_CSHARP_GCP#9]
On our github actions, we use a google token access in order to run the tests.

The issue is that we can't generate a permanent / durable access token, meaning that after one hour the automatic checks will fail.

A temporary fix is to update the "GCP_TOKEN" secret with a new key `gcloud auth application-default print-access-token` and to re-run the jobs.

**Comment by NicolasGlassey** [comment]
@MauroWasTaken @Penfu 

I'll see if I can fix it in gcp. 

This weekend I'm on a case too complicated to free up time, but I'll look into it on Monday. No stress for the demo, I already talked about it with Armand.

See u

**Comment by NicolasGlassey** [comment]
@MauroWasTaken 

This documentation seems to me to contain the solution that interests you...

https://www.googlecloudcommunity.com/gc/Apigee/Creating-gcloud-print-access-token-programmatically/m-p/491045

**Comment by MauroWasTaken** [comment]
We ended up getting a token with google credentials file.

here's the code we used to accomplish this
https://github.com/DinoChiesa/get-gcp-access-token/tree/main/dotnet/GetAccessTokenForServiceAccount
